# Generated by Django 6.0.3 on 2026-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='original_url',
            new_name='long_url',
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
